# Generated by Django 4.2.3 on 2023-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('preco', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
